export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const SET_PANEL = "SET_PANEL";
export const SET_ALL_FLIGHTS = "SET_ALL_FLIGHTS";
export const SET_FLIGHTS_FROM_AIRPORT = "SET_FLIGHTS_FROM_AIRPORT";
export const SET_AVAILABLE_FLIGHTS_FROM_TO = "SET_AVAILABLE_FLIGHTS_FROM_TO";
